import time
import unittest
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class TestLogin(unittest.TestCase):

    def test_system_message(self):
        browser = webdriver.Chrome()
        browser.get('http://localhost:5173')
        wait = WebDriverWait(browser, 5)
        el1 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="app"]/div[1]/div[1]/div[1]')))
        browser.execute_script("arguments[0].scrollIntoView();", el1)
        action = ActionChains(browser)
        action.move_to_element(el1).click().perform()
        el2 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="login"]/div/div[2]/input')))
        el2.send_keys('Nzh')
        time.sleep(2)
        el3 = browser.find_element(By.XPATH, '//*[@id="login"]/div/div[4]/input')
        el3.send_keys('Nzh123456')
        self.assertEqual(el2.get_attribute('value'), 'Nzh')
        self.assertEqual(el3.get_attribute('value'), 'Nzh123456')
        time.sleep(2)
        el4 = browser.find_element(By.XPATH, '//*[@id="login"]/div/button')
        browser.execute_script("arguments[0].scrollIntoView();", el4)
        action = ActionChains(browser)
        action.move_to_element(el4).click().perform()
        time.sleep(2)
        el6 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[1]/div[9]/div')))
        browser.execute_script("arguments[0].scrollIntoView();", el6)
        action = ActionChains(browser)
        action.move_to_element(el6).click().perform()
        time.sleep(2)
        el7 = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,
                                                         r'#app > div.flex.w-full.h-screen.bg-zinc-900 > div.w-full.lg\:w-5\/6.h-full.mr-0 > div > div > div.flex-1 > div.overflow-x-auto.px-10 > table > tbody > tr:nth-child(1)')))
        browser.execute_script("arguments[0].scrollIntoView();", el7)
        action = ActionChains(browser)
        action.move_to_element(el7).click().perform()
        el8 = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, r'#modal > div')))
        self.assertTrue(el8)

        browser.quit()

    def test_comment_message(self):
        browser = webdriver.Chrome()
        browser.get('http://localhost:5173')
        wait = WebDriverWait(browser, 5)
        el1 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="app"]/div[1]/div[1]/div[1]')))
        browser.execute_script("arguments[0].scrollIntoView();", el1)
        action = ActionChains(browser)
        action.move_to_element(el1).click().perform()
        el2 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="login"]/div/div[2]/input')))
        el2.send_keys('Nzh')
        time.sleep(2)
        el3 = browser.find_element(By.XPATH, '//*[@id="login"]/div/div[4]/input')
        el3.send_keys('Nzh123456')
        self.assertEqual(el2.get_attribute('value'), 'Nzh')
        self.assertEqual(el3.get_attribute('value'), 'Nzh123456')
        time.sleep(2)
        el4 = browser.find_element(By.XPATH, '//*[@id="login"]/div/button')
        browser.execute_script("arguments[0].scrollIntoView();", el4)
        action = ActionChains(browser)
        action.move_to_element(el4).click().perform()
        time.sleep(2)
        el6 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[1]/div[9]/div')))
        browser.execute_script("arguments[0].scrollIntoView();", el6)
        action = ActionChains(browser)
        action.move_to_element(el6).click().perform()
        time.sleep(2)
        el7 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[3]/div/div/div[1]/div[2]')))
        browser.execute_script("arguments[0].scrollIntoView();", el7)
        action = ActionChains(browser)
        action.move_to_element(el7).click().perform()
        time.sleep(2)
        el8 = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,
                                                         r'#app > div.flex.w-full.h-screen.bg-zinc-900 > div.w-full.lg\:w-5\/6.h-full.mr-0 > div > div > div.flex-1 > div > table > tbody > tr')))
        browser.execute_script("arguments[0].scrollIntoView();", el8)
        action = ActionChains(browser)
        action.move_to_element(el8).click().perform()
        # el9 = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,
        #                                                  r'#app > div.flex.w-full.h-screen.bg-zinc-900 > div.w-full.lg\:w-5\/6.h-full.mr-0 > div > div > div.flex-1 > div > div.mx-20')))
        # self.assertTrue(el9)
        browser.quit()

    def test_private_message(self):
        browser = webdriver.Chrome()
        browser.get('http://localhost:5173')
        wait = WebDriverWait(browser, 5)
        el1 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="app"]/div[1]/div[1]/div[1]')))
        browser.execute_script("arguments[0].scrollIntoView();", el1)
        action = ActionChains(browser)
        action.move_to_element(el1).click().perform()
        el2 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="login"]/div/div[2]/input')))
        el2.send_keys('Nzh')
        time.sleep(2)
        el3 = browser.find_element(By.XPATH, '//*[@id="login"]/div/div[4]/input')
        el3.send_keys('Nzh123456')
        self.assertEqual(el2.get_attribute('value'), 'Nzh')
        self.assertEqual(el3.get_attribute('value'), 'Nzh123456')
        time.sleep(2)
        el4 = browser.find_element(By.XPATH, '//*[@id="login"]/div/button')
        browser.execute_script("arguments[0].scrollIntoView();", el4)
        action = ActionChains(browser)
        action.move_to_element(el4).click().perform()
        time.sleep(2)
        el6 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[1]/div[9]/div')))
        browser.execute_script("arguments[0].scrollIntoView();", el6)
        action = ActionChains(browser)
        action.move_to_element(el6).click().perform()
        time.sleep(2)
        el7 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[3]/div/div/div[1]/div[3]')))
        browser.execute_script("arguments[0].scrollIntoView();", el7)
        action = ActionChains(browser)
        action.move_to_element(el7).click().perform()
        time.sleep(8)
        el8 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[3]/div/div/div[2]/div/div/div[1]/div[2]/div[2]')))
        browser.execute_script("arguments[0].scrollIntoView();", el8)
        action = ActionChains(browser)
        action.move_to_element(el8).click().perform()
        # el9 = wait.until(EC.presence_of_element_located((By.XPATH,
        #                                                  '//*[@id="app"]/div[1]/div[3]/div/div/div[2]/div/div/div[2]/div/div[1]/div')))
        # self.assertTrue(el9)
        browser.quit()

    def test_private_message_send(self):
        browser = webdriver.Chrome()
        browser.get('http://localhost:5173')
        wait = WebDriverWait(browser, 5)
        el1 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="app"]/div[1]/div[1]/div[1]')))
        browser.execute_script("arguments[0].scrollIntoView();", el1)
        action = ActionChains(browser)
        action.move_to_element(el1).click().perform()
        el2 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="login"]/div/div[2]/input')))
        el2.send_keys('Nzh')
        el3 = browser.find_element(By.XPATH, '//*[@id="login"]/div/div[4]/input')
        el3.send_keys('Nzh123456')
        self.assertEqual(el2.get_attribute('value'), 'Nzh')
        self.assertEqual(el3.get_attribute('value'), 'Nzh123456')
        el4 = browser.find_element(By.XPATH, '//*[@id="login"]/div/button')
        browser.execute_script("arguments[0].scrollIntoView();", el4)
        action = ActionChains(browser)
        action.move_to_element(el4).click().perform()
        time.sleep(2)
        el6 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[1]/div[9]/div')))
        browser.execute_script("arguments[0].scrollIntoView();", el6)
        action = ActionChains(browser)
        action.move_to_element(el6).click().perform()
        time.sleep(2)
        el7 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[3]/div/div/div[1]/div[3]')))
        browser.execute_script("arguments[0].scrollIntoView();", el7)
        action = ActionChains(browser)
        action.move_to_element(el7).click().perform()
        time.sleep(8)
        el8 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[3]/div/div/div[2]/div/div/div[1]/div[2]/div[2]')))
        browser.execute_script("arguments[0].scrollIntoView();", el8)
        action = ActionChains(browser)
        action.move_to_element(el8).click().perform()
        time.sleep(2)
        el9 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[3]/div/div/div[2]/div/div/div[2]/footer/div/input')))
        el9.send_keys('你好')
        time.sleep(2)
        self.assertEqual(el9.get_attribute('value'), '你好')

        browser.quit()

    def test_complaint_message(self):
        browser = webdriver.Chrome()
        browser.get('http://localhost:5173')
        wait = WebDriverWait(browser, 5)
        el1 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="app"]/div[1]/div[1]/div[1]')))
        browser.execute_script("arguments[0].scrollIntoView();", el1)
        action = ActionChains(browser)
        action.move_to_element(el1).click().perform()
        el2 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="login"]/div/div[2]/input')))
        el2.send_keys('Nzh')
        el3 = browser.find_element(By.XPATH, '//*[@id="login"]/div/div[4]/input')
        el3.send_keys('Nzh123456')
        self.assertEqual(el2.get_attribute('value'), 'Nzh')
        self.assertEqual(el3.get_attribute('value'), 'Nzh123456')
        el4 = browser.find_element(By.XPATH, '//*[@id="login"]/div/button')
        browser.execute_script("arguments[0].scrollIntoView();", el4)
        action = ActionChains(browser)
        action.move_to_element(el4).click().perform()
        time.sleep(2)
        el6 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[1]/div[9]/div')))
        browser.execute_script("arguments[0].scrollIntoView();", el6)
        action = ActionChains(browser)
        action.move_to_element(el6).click().perform()
        time.sleep(2)
        el7 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[3]/div/div/div[1]/div[4]')))
        browser.execute_script("arguments[0].scrollIntoView();", el7)
        action = ActionChains(browser)
        action.move_to_element(el7).click().perform()
        time.sleep(8)
        el8 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[3]/div/div/div[2]/div/table/tbody/tr[1]')))
        browser.execute_script("arguments[0].scrollIntoView();", el8)
        action = ActionChains(browser)
        action.move_to_element(el8).click().perform()
        time.sleep(2)
        el9 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[3]/div/div/div[2]/div/div[1]')))
        self.assertTrue(el9)
        browser.quit()

    def test_appeal_message(self):
        browser = webdriver.Chrome()
        browser.get('http://localhost:5173')
        wait = WebDriverWait(browser, 5)
        el1 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="app"]/div[1]/div[1]/div[1]')))
        browser.execute_script("arguments[0].scrollIntoView();", el1)
        action = ActionChains(browser)
        action.move_to_element(el1).click().perform()
        el2 = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="login"]/div/div[2]/input')))
        el2.send_keys('yy')
        el3 = browser.find_element(By.XPATH, '//*[@id="login"]/div/div[4]/input')
        el3.send_keys('2003')
        el4 = browser.find_element(By.XPATH, '//*[@id="login"]/div/button')
        browser.execute_script("arguments[0].scrollIntoView();", el4)
        action = ActionChains(browser)
        action.move_to_element(el4).click().perform()
        time.sleep(2)
        el6 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[1]/div[9]/div')))
        browser.execute_script("arguments[0].scrollIntoView();", el6)
        action = ActionChains(browser)
        action.move_to_element(el6).click().perform()
        time.sleep(2)
        el7 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[3]/div/div/div[1]/div[5]')))
        browser.execute_script("arguments[0].scrollIntoView();", el7)
        action = ActionChains(browser)
        action.move_to_element(el7).click().perform()
        time.sleep(8)
        el8 = wait.until(EC.presence_of_element_located((By.XPATH,
                                                         '//*[@id="app"]/div[1]/div[3]/div/div/div[2]/div[1]')))
        browser.execute_script("arguments[0].scrollIntoView();", el8)
        action = ActionChains(browser)
        action.move_to_element(el8).click().perform()
        time.sleep(2)
        el9 = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,
                                                         r'#app > div.flex.w-full.h-screen.bg-zinc-900 > div.w-full.lg\:w-5\/6.h-full.mr-0 > div > div > div.flex-1 > div.transition-container-2')))
        self.assertTrue(el9)
        browser.quit()


if __name__ == "__main__":
    unittest.main()
