# Generated by Django 5.0.4 on 2024-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_alter_song_tag_mood'),
        ('songlist', '0002_alter_songlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlist',
            name='songs',
            field=models.ManyToManyField(to='song.song', verbose_name='包含的歌曲'),
        ),
        migrations.AlterField(
            model_name='songlist',
            name='tag_mood',
            field=models.CharField(blank=True, choices=[('伤感', '伤感'), ('安静', '安静'), ('思念', '思念'), ('宣泄', '宣泄'), ('开心', '开心')], max_length=100, null=True, verbose_name='心情标签'),
        ),
    ]
