# Generated by Django 5.0.4 on 2024-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_song_gradient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tag_mood',
            field=models.CharField(blank=True, choices=[('伤感', '伤感'), ('安静', '安静'), ('思念', '思念'), ('宣泄', '宣泄'), ('开心', '开心')], max_length=100, null=True, verbose_name='心情标签'),
        ),
    ]
