# Generated by Django 5.0.4 on 2024-04-26 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0006_alter_song_tag_mood'),
        ('user', '0004_alter_user_avatar_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_play', models.DateTimeField(auto_now_add=True, verbose_name='最近一次播放时间')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放次数')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song', verbose_name='歌曲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'unique_together': {('user', 'song')},
            },
        ),
    ]
